// import 'dart:convert';
//
// import 'package:flutter/material.dart';
// import 'package:flutter/services.dart';
// import 'package:flutter_svg/flutter_svg.dart';
// import 'package:rydyt_expense_v_one/test_response.dart';
// import 'package:toggle_switch/toggle_switch.dart';
// import 'package:fl_chart/fl_chart.dart';
//
//
// class pieScreen extends StatefulWidget {
//   pieScreen({super.key});
//
//   @override
//   State<pieScreen> createState() => _pieScreenState();
// }
//
// class _pieScreenState extends State<pieScreen> {
//   var selectedToggleIndex = 0;
//   var categoryToggleIndex = 0;
//   var simpleToggleIndex = 0;
//   var selectedtoggleIndex = 0;
//   var selecttoggleIndex = 0;
//   Autogenerated? obj;
//   double total = 0;
//   List<int> selectedCategories = [];
//
//   List assetpath1 = [
//     "assets/images/bikers_img.jpeg",
//     "assets/images/bikers_img2.jpeg",
//     "assets/images/bikers_img3.jpeg",
//     "assets/images/bikers_img4.jpeg",
//     "assets/images/bikers_img5.jpeg",
//     "assets/images/bikers_img6.jpeg",
//     "assets/images/bikers_img7.jpeg",
//     "assets/images/bikers_img8.jpeg",
//     "assets/images/bikers_img9.jpeg",
//     "assets/images/bikers_img10.jpeg",
//   ];
//
//   List peopleCataText1 = [
//     "ALL",
//     "DAVID",
//     "RAK",
//     "KUSHANG",
//     "KHALIL",
//     "MIKE",
//     "DHRUVA",
//     "NEERAJ",
//     "DEEPTHI",
//     "KASISH",];
//
//   List cateCataIcons = [
//     "assets/icons/fuel_icon.svg",
//     "assets/icons/food_icon.svg",
//     "assets/icons/hotel_icon.svg",
//     "assets/icons/grocery_icon.svg",
//     "assets/icons/otherRuppe_icon.svg"];
//
//   List cateCatatext = ["Fuel","Food","Hotel","Grocery","Others"];
//
//
//   void initState() {
//     readJson();
//     super.initState();
//
//   }
//   Future<void> readJson() async {
//     final String response = await rootBundle.loadString('assets/test.json');
//     obj = Autogenerated.fromJson(json.decode(response));
//
//   }
//
//   @override
//   Widget build(BuildContext context) {
//     List Kushang = ['Kushang','Kushang'];
//     List yourExpenseList = ['You', 'Kumar', 'Ram', 'Raj', 'Kushang'];
//     List categoryList = ['fuel', 'food', 'rent', 'others', 'shopping'];
//     List expense = ['1000', '2000', '3000', '4000', '5000'];
//
//     List headNameList =["Kushang","Khalil","Ram","Deepthi","Dhruva",];
//     List headAmountList =["1000","1255","2341","2300","1438",];
//     List subHeadCataList =["Fuel","Fuel","Fuel","Fuel","Fuel",];
//     List subHeadTimeList =["03:30 pm","03:30 pm","03:30 pm","03:30 pm","03:30 pm",];
//
//     List assetpath = [
//       "assets/icons/fuel_icon.svg",
//       "assets/icons/food_icon.svg",
//       "assets/icons/hotel_icon.svg",
//       "assets/icons/grocery_icon.svg",
//       "assets/icons/otherRuppe_icon.svg"];
//
//     List text = ["Fuel","Food","Hotel","Grocery","Others"];
//
//     return Scaffold(
//       backgroundColor: Colors.black,
//       body: Padding(
//         padding: const EdgeInsets.only(top: 16, left: 16, right: 16),
//         child: ListView(
//           children: [
//             Padding(
//               padding: const EdgeInsets.only(top: 30),
//               child: Row(
//                 children: [
//                   Text(
//                     "Ride Expenses",
//                     style: TextStyle(
//                         fontSize: 24,
//                         fontWeight: FontWeight.w400,
//                         color: Colors.white),
//                   ),
//                   Spacer(),
//                   IconButton(onPressed: (){
//                     Navigator.pop(context);
//                   }, icon: Icon(Icons.close),)
//                 ],
//               ),
//             ),
//             SizedBox(height: 30,),
//             Row(mainAxisAlignment: MainAxisAlignment.center,
//               children: [
//                 Container(
//                   height: 33,
//                   width: 200,
//                   child: ToggleSwitch(
//                     cornerRadius: 5,
//                     radiusStyle: true,
//                     initialLabelIndex: selectedtoggleIndex,
//                     minWidth: 150,
//                     minHeight: 30,
//                     activeBgColor: [Color(0xFFEB1D23),Color(0xFFEB1D23).withOpacity(0.5)],
//                     activeFgColor: Colors.white,
//                     inactiveBgColor: Colors.white10,
//                     inactiveFgColor: Colors.white,
//                     totalSwitches: 2,
//                     labels: ['You','All'],
//                     onToggle: (index){
//                       setState(() {
//                         selectedtoggleIndex = index!;
//                       });
//                     },
//                   ),
//                 ),
//               ],
//             ),
//             SizedBox(height: 30,),
//             Container(
//               child: ToggleSwitch(
//                 cornerRadius: 0,
//                 initialLabelIndex: selectedToggleIndex,
//                 activeBorders: [Border(bottom: BorderSide(color: Colors.red, width: 1,),)],
//                 minWidth: MediaQuery.of(context).size.width / 3, // Split evenly for 3 buttons
//                 minHeight: 40,
//                 activeBgColor: [Colors.black],
//                 activeFgColor: Colors.red,
//                 inactiveBgColor: Colors.black,
//                 inactiveFgColor: Colors.white,
//                 totalSwitches: 3,
//                 labels: ['Common', 'Individual', 'Only Me'],
//                 onToggle: (index) {
//                   setState(() {
//                     selectedToggleIndex = index!;
//                   });
//                 },
//               ),
//             ),
//
//             if(selectedToggleIndex == 0) ...[
//               Padding(
//                 padding: const EdgeInsets.only(top: 30,),
//                 child: Container(
//                     decoration: BoxDecoration(border: Border.all(color: Color(0x34ffffff),width: 1),borderRadius: BorderRadius.circular(20)),
//                     child: Padding(
//                       padding: const EdgeInsets.all(20),
//                       child: Column(
//                         children: [
//                           Container(
//                             height: 200,
//                             width: 200,
//                             child: Container(
//                               child: PieChart(
//                                   PieChartData(
//                                     sections: [
//                                       PieChartSectionData(
//                                         gradient: LinearGradient(colors: [Color(0xffFFC700),Color(0xff997700)]),
//                                         value: 25,
//                                         title: '',
//                                         radius: 20,
//                                         titleStyle: TextStyle(
//                                           fontSize: 16,
//                                           fontWeight: FontWeight.bold,
//                                           color: Colors.white,
//                                         ),
//                                       ),
//                                       PieChartSectionData(
//                                         gradient:
//                                         LinearGradient(
//                                             begin: Alignment.centerLeft,
//                                             end: Alignment.centerRight,
//                                             colors: [Color(0xFFDD6762),Color(0xFFDD695E).withOpacity(0.8)]),
//                                         value: 12.5,
//                                         title: '',
//
//                                         radius: 20,
//                                         titleStyle: TextStyle(
//                                           fontSize: 16,
//                                           fontWeight: FontWeight.bold,
//                                           color: Colors.white,
//                                         ),
//                                       ),
//                                       PieChartSectionData(
//                                         gradient: LinearGradient(colors: [Color(0xFFEB2EEF),Color(0xFFEB2EEF).withOpacity(0.7)]),
//                                         value: 12.5,
//                                         title: '',
//
//                                         radius: 20,
//                                         titleStyle: TextStyle(
//                                           fontSize: 16,
//                                           fontWeight: FontWeight.bold,
//                                           color: Colors.white,
//                                         ),
//                                       ),
//                                       PieChartSectionData(
//                                         gradient: LinearGradient(colors: [Color(0xff1993F6),Color(0xff0F5690)]) ,
//                                         value: 25,
//                                         title: '',
//
//                                         radius: 20,
//                                         titleStyle: TextStyle(
//                                           fontSize: 16,
//                                           fontWeight: FontWeight.bold,
//                                           color: Colors.white,
//                                         ),
//                                       ),
//                                       PieChartSectionData(
//                                         gradient: LinearGradient(colors: [Color(0xff42CFA3),Color(0xff216953)]) ,
//                                         value: 25,
//                                         title: '',
//
//
//                                         radius: 20,
//                                         titleStyle: TextStyle(
//                                           fontSize: 16,
//                                           fontWeight: FontWeight.bold,
//                                           color: Colors.white,
//                                         ),
//                                       ),
//                                     ],
//                                   )
//                               ),
//                             ),
//                           ),
//                           SizedBox(height: 20),
//                           SingleChildScrollView(
//                             scrollDirection: Axis.horizontal,
//                             child: Row(mainAxisAlignment: MainAxisAlignment.center,
//                               children: [
//                                 Container(
//                                   decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xFFFFC700),Color(0xFF997700)]),borderRadius: BorderRadius.circular(4)),
//                                   child: Padding(
//                                     padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
//                                     child: Text("YOU",style: TextStyle(fontWeight: FontWeight.w400,fontSize: 12,color: Colors.white.withOpacity(0.8),fontFamily: "FontPoppins"),),
//                                   ),
//                                 ),
//                                 SizedBox(width: 15,),
//                                 Container(
//                                   decoration: BoxDecoration(
//                                       gradient: LinearGradient(
//                                           begin: Alignment.centerLeft,
//                                           end: Alignment.centerRight,
//                                           colors: [Color(0xFFDD6762),Color(0xFFDD695E).withOpacity(0.8)]),borderRadius: BorderRadius.circular(4)),
//                                   child: Padding(
//                                     padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
//                                     child: Text("KUMAR",style: TextStyle(fontWeight: FontWeight.w400,fontSize: 12,color: Colors.white.withOpacity(0.8),fontFamily: "FontPoppins"),),
//                                   ),
//                                 ),
//                                 SizedBox(width: 15,),
//                                 Container(
//                                   decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xFFEB2EEF),Color(0xFFEB2EEF).withOpacity(0.7)]) ,borderRadius: BorderRadius.circular(4)),
//
//                                   child: Padding(
//                                     padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
//                                     child: Text("RAM",style: TextStyle(fontWeight: FontWeight.w400,fontSize: 12,color: Colors.white.withOpacity(0.8),fontFamily: "FontPoppins"),),
//                                   ),
//                                 ),
//                                 SizedBox(width: 15,),
//                                 Container(
//                                   decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xff42CFA3),Color(0xff216953)]) ,borderRadius: BorderRadius.circular(4)),
//                                   height: 30,
//
//                                   child: Padding(
//                                     padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
//                                     child: Text("RAJ",style: TextStyle(fontWeight: FontWeight.w400,fontSize: 12,color: Colors.white.withOpacity(0.8),fontFamily: "FontPoppins"),),
//                                   ),
//                                 ),
//                                 SizedBox(width: 15,),
//                                 Container(
//                                   decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xff1993F6),Color(0xff0F5690)]) ,borderRadius: BorderRadius.circular(4)),
//                                   height: 30,
//
//                                   child: Padding(
//                                     padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
//                                     child: Text("KUSHANG",style: TextStyle(fontWeight: FontWeight.w400,fontSize: 12,color: Colors.white.withOpacity(0.8),fontFamily: "FontPoppins"),),
//                                   ),
//                                 )
//                               ],
//                             ),
//                           ),
//                           Padding(
//                             padding: const EdgeInsets.only(top: 20),
//                             child: Row(mainAxisAlignment: MainAxisAlignment.center,
//                               children: [
//                                 Container(
//                                   height: 33,
//                                   width: 200,
//                                   child: ToggleSwitch(
//                                     cornerRadius: 5,
//                                     radiusStyle: true,
//                                     initialLabelIndex: selecttoggleIndex,
//                                     minWidth: 150,
//                                     minHeight: 30,
//                                     activeBgColor: [Color(0xFFEB1D23),Color(0xFFEB1D23).withOpacity(0.5)],
//                                     activeFgColor: Colors.white,
//                                     inactiveBgColor: Colors.white10,
//                                     inactiveFgColor: Colors.white,
//                                     totalSwitches: 2,
//                                     labels: ['Person','Category'],
//                                     onToggle: (index){
//                                       setState(() {
//                                         selecttoggleIndex = index!;
//                                       });
//                                     },
//                                   ),
//                                 ),
//                               ],
//                             ),
//                           ),
//                         ],
//                       ),
//                     )
//                 ),
//               ),
//               SizedBox(height: 30,),
//               Container(
//                 width: double.infinity,
//                 decoration: BoxDecoration(
//                   gradient: LinearGradient(
//                     colors: [Color(0xFF535353).withOpacity(0.0),Color(0xFF5B5B5B).withOpacity(0.5)],
//                   ),
//                   borderRadius: BorderRadius.circular(10),
//                   border: Border.all(color: Colors.white12,width: 1),
//                 ),
//                 child: Row(
//                   children: [
//                     Padding(
//                       padding: const EdgeInsets.all(10.0),
//                       child: Text("Your Balance:",style: TextStyle(color: Colors.white,fontSize: 16,fontWeight: FontWeight.w500,fontFamily: "FontPoppins"),),
//                     ),
//                     SizedBox(width: 5),
//                     Padding(
//                       padding: const EdgeInsets.only(top: 10,bottom:10 ),
//                       child: Text("₹ 1000",style: TextStyle(color: Colors.green,fontSize: 16,fontWeight: FontWeight.w500,fontFamily: "FontPoppins"),),
//                     ),Spacer(),
//                     Padding(
//                       padding: const EdgeInsets.only(right: 10),
//                       child: Text("Yet to pay",style: TextStyle(color: Colors.white.withOpacity(0.5),fontFamily: "FontPoppins"),),
//                     )
//                   ],
//                 ),
//               ),
//               SizedBox(height: 15,),
//               Padding(
//                 padding: const EdgeInsets.only(top: 15),
//                 child: InkWell(
//                   onTap: (){
//                     _modalBottomSheetMenu();
//                   },
//                   child: Container(
//                     width: double.infinity,
//                     decoration: BoxDecoration(
//                       gradient: LinearGradient(
//                           colors: [Color(0xFFD9D9D9).withOpacity(0.2),Color(0xFF5B5B5B).withOpacity(0.4),]),
//                       borderRadius: BorderRadius.circular(40),
//                       border: Border.all(color: Colors.white12,width: 1),
//                     ),
//                     child: Center(
//                       child: Padding(
//                         padding: const EdgeInsets.only(top: 11,bottom: 11),
//                         child: Text("View Summary",
//                             style: TextStyle(
//                                 fontSize: 12,
//                                 fontWeight: FontWeight.w400,
//                                 color: Colors.white.withOpacity(0.7)
//                             )),
//                       ),
//                     ),
//                   ),
//                 ),
//               ),
//               SizedBox(height: 30,),
//               Row(
//                 children: [
//                   Text(
//                     "Expenses for this ride",
//                     style: TextStyle(fontSize: 24, fontWeight: FontWeight.w400,color: Colors.white,fontFamily: "FontPoppins"),
//                   ),
//                   Spacer(),
//                   InkWell(
//                       onTap: (){
//                         showModalBottomSheet(
//                             backgroundColor: Colors.black,
//                             enableDrag: true,
//                             shape: RoundedRectangleBorder(
//                               borderRadius: BorderRadius.only(
//                                 topRight: Radius.circular(20),
//                                 topLeft: Radius.circular(20),
//                               ),
//                               side: BorderSide(color: Colors.white12,width: 1)
//                             ),
//                             context: context, builder: (context){
//                               return Padding(
//                                 padding: const EdgeInsets.only(left: 18,right: 14),
//                                 child: SingleChildScrollView(
//                                //   scrollDirection: Axis.horizontal,
//                                   child: Column(crossAxisAlignment: CrossAxisAlignment.start,mainAxisSize: MainAxisSize.min,
//                                     children: [
//                                       Padding(
//                                       padding: const EdgeInsets.only(top: 42),
//                                       child: Row(
//                                         children: [
//                                           Text("Filter",
//                                               style: TextStyle(
//                                                   fontSize: 24,
//                                                   fontWeight: FontWeight.w400,
//                                                   color: Colors.white,
//                                                   fontFamily: "FontPoppins")),
//                                           Spacer(),
//                                           GestureDetector(
//                                               onTap: () => Navigator.pop(context),
//                                               child: SvgPicture.asset("assets/icons/cross_icon.svg"))
//                                         ],
//                                       ),
//                                     ),
//                                       SizedBox(height: 23,),
//                                       Row(mainAxisAlignment: MainAxisAlignment.start,
//                                         children: [
//                                           Text("People",style: TextStyle(color: Colors.white,
//                                               fontSize: 16,
//                                               fontWeight: FontWeight.w400,
//                                               fontFamily: "FontPoppins"),),
//                                           Spacer(),
//                                           Text("10/10",style: TextStyle(color: Colors.white.withOpacity(0.7),
//                                               fontSize: 16,
//                                               fontWeight: FontWeight.w400,
//                                               fontFamily: "FontPoppins"))
//                                         ],
//                                       ),
//                                       SizedBox(height: 10,),
//                                       SizedBox(height: 100,
//                                         child: ListView.builder(
//                                             scrollDirection: Axis.horizontal,
//                                             itemCount: peopleCataText1.length,
//                                             itemBuilder: (context,index){
//                                               return peopleCata(assetpath1[index], peopleCataText1[index]);
//                                             }),
//                                       ),
//                                       SizedBox(height: 20,),
//                                       Row(mainAxisAlignment: MainAxisAlignment.start,
//                                         children: [
//                                           Text("Category",style: TextStyle(color: Colors.white,
//                                               fontSize: 16,
//                                               fontWeight: FontWeight.w400,
//                                               fontFamily: "FontPoppins"),),
//                                           Spacer(),
//                                           Text("1/6",style: TextStyle(color: Colors.white.withOpacity(0.7),
//                                               fontSize: 16,
//                                               fontWeight: FontWeight.w400,
//                                               fontFamily: "FontPoppins"))
//                                         ],
//                                       ),
//                                       SizedBox(height: 10,),
//                                       SizedBox(height: 100,
//                                         child: ListView.builder(
//                                           shrinkWrap: true,
//                                             scrollDirection: Axis.horizontal,
//                                             itemCount: cateCataIcons.length,
//                                             itemBuilder: (context,index){
//                                               return cata(cateCataIcons[index], cateCatatext[index]);
//                                             }),
//                                       ),
//                                       SizedBox(height: 20,),
//                                       Container(
//                                         width: double.infinity,
//                                         decoration:  BoxDecoration(
//                                           gradient: LinearGradient(colors: [Color(0xFFEB1D23),Color(0xFFEB1D23).withOpacity(0.5)]),
//                                           borderRadius: BorderRadius.circular(27),
//                                           border: Border.all(
//                                             width: 1,
//                                             color: Colors.red.withOpacity(0.4),
//                                           ),
//                                         ),
//                                         child:
//                                         Padding(
//                                           padding: const EdgeInsets.only(top: 9.5,bottom: 9.5),
//                                           child: Text("Apply Flitter",
//                                                   style: TextStyle(
//                                                     color: Colors.white,
//                                                     fontFamily: "FontPoppins",
//                                                     fontWeight: FontWeight.w400,
//                                                     fontSize: 14,
//                                                   ),textAlign: TextAlign.center)
//
//                                         ),
//                                       ),
//                                   ],),
//                                 ),
//                               );
//                         });
//                       },
//                       child: SvgPicture.asset("assets/icons/setting_icon.svg")),
//                 ],
//               ),
//               SizedBox(height: 15,),
//               Row(
//                 children: [
//                   Expanded(child: Text("23 Apr 2024",style: TextStyle(fontSize: 12,fontWeight: FontWeight.w400,color: Colors.white.withOpacity(0.9),fontFamily: "FontPoppins"),)),
//                   Text("₹ ${8790}",style: TextStyle(fontSize: 12,fontWeight: FontWeight.w400,color: Colors.white.withOpacity(0.9),fontFamily: "FontPoppins"))
//                 ],
//               ),
//               Container(
//                   width: double.infinity,
//                   child: ListView.builder(
//                       itemCount: headNameList.length,
//                       shrinkWrap: true,
//                       itemBuilder: (context, index) {
//                         return Padding(
//                           padding: const EdgeInsets.only(top: 10.0,bottom: 10.0),
//                           child: Container(
//                             decoration: BoxDecoration(
//                                 color: Color(0x1affffff),
//                                 borderRadius: BorderRadius.circular(10)),
//                             child: ListTile(
//                                 title: Row(
//                                   children: [
//                                     Expanded(child: Text(headNameList[index],style: TextStyle(fontSize: 16,fontWeight: FontWeight.w400,color: Colors.white.withOpacity(0.9),fontFamily: "FontPoppins"))),
//                                     Text("₹ ${headAmountList[index]}",style: TextStyle(fontSize: 16,fontWeight: FontWeight.w400,color: Colors.white.withOpacity(0.9),fontFamily: "FontPoppins")),
//                                   ],
//                                 ),
//                                 subtitle: Column(
//                                     children: [
//                                       Row(
//                                         children: [
//                                           Expanded(child: Text(subHeadCataList[index],style: TextStyle(fontSize: 12,fontWeight: FontWeight.w400,color: Colors.white.withOpacity(0.5),fontFamily: "FontPoppins"))),
//                                           Text(subHeadTimeList[index],style: TextStyle(fontSize: 12,fontWeight: FontWeight.w400,color: Colors.white.withOpacity(0.5),fontFamily: "FontPoppins")),
//                                         ],
//                                       )])),
//                           ),
//                         );
//                       }))
//
//             ]
//             else if(selectedToggleIndex == 1) ...[
//               Column(
//                 children: [
//                   Padding(
//                     padding: const EdgeInsets.only(top: 30, bottom: 30),
//                     child: Container(
//                         decoration: BoxDecoration(border: Border.all(color: Color(0x34ffffff),width: 1),borderRadius: BorderRadius.circular(20)),
//                         child:
//
//                         Padding(
//                           padding: const EdgeInsets.all(20),
//                           child: Column(
//                             children: [
//                               Container(height: 200,
//                                 width: 200,
//                                 child: Container(
//
//                                   child: PieChart(
//                                       PieChartData(
//                                         sections: [
//                                           PieChartSectionData(
//                                             gradient: LinearGradient(colors: [Color(0xffFFC700),Color(0xff997700)]),
//                                             value: 25,
//                                             title: '',
//
//                                             radius: 20,
//                                             titleStyle: TextStyle(
//                                               fontSize: 16,
//                                               fontWeight: FontWeight.bold,
//                                               color: Theme.of(context).colorScheme.onPrimary,
//                                             ),
//                                           ),
//                                           PieChartSectionData(
//                                             gradient:
//                                             LinearGradient(
//                                                 begin: Alignment.centerLeft,
//                                                 end: Alignment.centerRight,
//
//                                                 colors: [Color(0xFFDD6762),Color(0xFFDD695E).withOpacity(0.8)]),
//                                             value: 12.5,
//                                             title: '',
//
//                                             radius: 20,
//                                             titleStyle: TextStyle(
//                                               fontSize: 16,
//                                               fontWeight: FontWeight.bold,
//                                               color: Theme.of(context).colorScheme.onPrimary,
//                                             ),
//                                           ),
//                                           PieChartSectionData(
//                                             gradient: LinearGradient(colors: [Color(0xFFEB2EEF),Color(0xFFEB2EEF).withOpacity(0.7)]),
//                                             value: 12.5,
//                                             title: '',
//
//                                             radius: 20,
//                                             titleStyle: TextStyle(
//                                               fontSize: 16,
//                                               fontWeight: FontWeight.bold,
//                                               color: Theme.of(context).colorScheme.onPrimary,
//                                             ),
//                                           ),
//                                           PieChartSectionData(
//                                             gradient: LinearGradient(colors: [Color(0xff1993F6),Color(0xff0F5690)]) ,
//                                             value: 25,
//                                             title: '',
//
//                                             radius: 20,
//                                             titleStyle: TextStyle(
//                                               fontSize: 16,
//                                               fontWeight: FontWeight.bold,
//                                               color: Theme.of(context).colorScheme.onSecondary,
//                                             ),
//                                           ),
//                                           PieChartSectionData(
//                                             gradient: LinearGradient(colors: [Color(0xff42CFA3),Color(0xff216953)]) ,
//                                             value: 25,
//                                             title: '',
//
//
//                                             radius: 20,
//                                             titleStyle: TextStyle(
//                                               fontSize: 16,
//                                               fontWeight: FontWeight.bold,
//                                               color: Theme.of(context).colorScheme.onError,
//                                             ),
//                                           ),
//                                         ],
//                                       )
//                                   ),
//                                 ),
//                               ),
//                               Padding(
//                                 padding: const EdgeInsets.only(top: 20.0,bottom: 20.0),
//                                 child: SingleChildScrollView(
//                                   scrollDirection: Axis.horizontal,
//                                   child: Row(mainAxisAlignment: MainAxisAlignment.center,
//
//                                     children: [
//                                       Container(
//                                         decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xffFFC700),Color(0xff997700)]),borderRadius: BorderRadius.circular(4)),
//                                         height: 30,
//
//                                         child: Padding(
//                                           padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
//                                           child: Text("YOU",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),),
//                                         ),
//                                       ),
//                                       SizedBox(width: 10,)
//                                       ,Container(
//                                         decoration: BoxDecoration(
//                                             gradient:
//                                             LinearGradient(
//                                                 begin: Alignment.centerLeft,
//                                                 end: Alignment.centerRight,
//
//                                                 colors: [Color(0xFFDD6762),Color(0xFFDD695E).withOpacity(0.8)]),borderRadius: BorderRadius.circular(4)),
//                                         height: 30,
//
//                                         child: Padding(
//                                           padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
//                                           child: Text("Kumar",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),),
//                                         ),
//                                       ),SizedBox(width: 10,),Padding(
//                                         padding: const EdgeInsets.only(right: 15.0),
//                                         child: Container(
//                                           decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xFFEB2EEF),Color(0xFFEB2EEF).withOpacity(0.7)]) ,borderRadius: BorderRadius.circular(4)),
//                                           height: 30,
//
//                                           child: Padding(
//                                             padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
//                                             child: Text("Ram",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),),
//                                           ),
//                                         ),
//                                       ),Padding(
//                                         padding: const EdgeInsets.only(right: 15.0),
//                                         child: Container(
//                                           decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xff42CFA3),Color(0xff216953)]) ,borderRadius: BorderRadius.circular(4)),
//                                           height: 30,
//
//                                           child: Padding(
//                                             padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
//                                             child: Text("Raj",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),),
//                                           ),
//                                         ),
//                                       ),Padding(
//                                         padding: const EdgeInsets.only(right: 15.0),
//                                         child: Container(
//                                           decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xff1993F6),Color(0xff0F5690)]) ,borderRadius: BorderRadius.circular(4)),
//                                           height: 30,
//
//                                           child: Padding(
//                                             padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
//                                             child: Text("Kushang",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),),
//                                           ),
//                                         ),
//                                       )
//                                     ],
//                                   ),
//                                 ),
//
//                               ),
//                               Row(mainAxisSize: MainAxisSize.min,mainAxisAlignment: MainAxisAlignment.center,crossAxisAlignment: CrossAxisAlignment.center,
//                                 children: [
//                                   ToggleSwitch(
//
//                                     minWidth: 93.0,
//
//                                     //customWidths: const [93,93],
//
//
//                                     radiusStyle: true,
//                                     labels: ['Person','Category'],
//                                     initialLabelIndex: 0,
//                                     cornerRadius: 4,
//                                     activeFgColor: Colors.white,
//                                     inactiveFgColor: Colors.white,
//                                     activeBgColors: [
//                                       [Color(0xffEB1D23), Color(0xff840004),], // Gradient for Active
//                                       [Color(0xffEB1D23), Color(0xff840004),],  // Gradient for Inactive
//                                     ],
//                                     inactiveBgColor: Color(0x47292424),
//
//
//                                     onToggle: (index) {
//                                       setState(() {
//                                         categoryToggleIndex = index!;
//                                       });
//                                     },
//                                   ),
//                                 ],
//                               )
//                             ],
//                           ),
//                         )
//
//
//
//                     ),
//                   ),
//
//                   ElevatedButton(onPressed: (){
//
//                   }, child:Padding(
//                     padding: const EdgeInsets.only(bottom: 20),
//                     child: Container(decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xff5b5b5b),Color(
//                         0xff333131)]),borderRadius: BorderRadius.circular(40)),
//
//                       child: ElevatedButton(onPressed: (){
//
//                         _modalBottomSheetMenu();
//
//
//                       }, child: Text("View Summary",style: TextStyle(color: Colors.white),)
//                         ,style: ElevatedButton.styleFrom(
//                           backgroundColor: Colors.transparent,
//                           minimumSize: Size(MediaQuery.of(context).size.width, 50),
//                           shape: RoundedRectangleBorder(
//                             borderRadius: BorderRadius.circular(40),
//                           ),
//                         ),),
//                     ),
//                   ),),
//                   Row(
//                     children: [
//                       Text(
//                         "Individual Expenses",
//                         style: TextStyle(fontSize: 24, fontWeight: FontWeight.w400),
//                       ),
//                       Spacer(),
//                       Icon(Icons.sort),
//                     ],
//                   ),
//
//
//                   Padding(
//                     padding: const EdgeInsets.only(top: 20),
//                     child: Row(
//                       children: [
//                         Container(
//                           decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xff5B5B5B),Color(0xff333131)]),borderRadius: BorderRadius.circular(4)),
//                           height: 30,
//
//                           child: Padding(
//                             padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
//                             child: Row(
//                               children: [
//                                 Text("Ram",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),),
//                                 SizedBox(width: 5,),
//                                 Icon(Icons.close,size: 18,)
//                               ],
//                             ),
//                           ),
//
//                         ),SizedBox(width: 10,),Container(
//                           decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xff5B5B5B),Color(0xff333131)]),borderRadius: BorderRadius.circular(4)),
//                           height: 30,
//
//                           child: Padding(
//                             padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
//                             child: Row(
//                               children: [
//                                 Text("Kushang",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),),
//                                 SizedBox(width: 5,),
//                                 Icon(Icons.close,size: 18,)
//                               ],
//                             ),
//                           ),
//                         ),
//                         SizedBox(width: 10,),
//                         Container(
//                           decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xff5B5B5B),Color(0xff333131)]),borderRadius: BorderRadius.circular(4)),
//                           height: 30,
//
//                           child: Padding(
//                             padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
//                             child: Row(
//                               children: [
//                                 Text("Fuel",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),),
//                                 SizedBox(width: 5,),
//                                 Icon(Icons.close,size: 18,)
//                               ],
//                             ),
//                           ),
//                         ),
//                       ],
//                     ),
//                   ),
//                   Padding(
//                     padding: const EdgeInsets.only(top: 20,bottom: 10),
//                     child: Row(children: [
//                       Expanded(child: Text("23 Apr 2024",style: TextStyle(fontSize: 12),)),
//                       Text("₹ 5000",style: TextStyle(fontSize: 12,color: Color(0xffffffff)),)
//
//                     ],
//
//
//                     ),
//                   ),
//                   Container(
//                     height: 300,
//                     child: ListView.builder(itemCount: 2,itemBuilder: (context,index){
//                       return Padding(
//                         padding: const EdgeInsets.only(top: 10,bottom: 10),
//                         child: Container(
//                           width: 380,
//                           decoration: BoxDecoration(color: Color(0x1affffff),borderRadius: BorderRadius.circular(10)),
//                           child: ListTile(
//                             title: Row(
//                               children: [
//                                 Expanded(child: Text("${Kushang[index]}",style: TextStyle(color: Colors.white, fontWeight: FontWeight.w400,fontSize: 24))),
//                                 Text("₹${expense[index]}",style: TextStyle(color: Theme.of(context).colorScheme.primary,fontSize: 20, fontWeight: FontWeight.w400))
//                               ],
//
//                             ),subtitle: Row(
//                               children: [Expanded(child: Text("${categoryList[index]}",style: TextStyle(color: Color(0x80ffffff), fontWeight: FontWeight.w400,fontSize: 18))),
//                                 Text("₹${expense[index]}",style: TextStyle(color: Color(0x80ffffff), fontWeight: FontWeight.w400,fontSize: 18))]
//
//                           ),
//                           ),
//                         ),
//                       );
//
//
//                     }
//
//
//
//
//                     ),
//                   )
//                 ],
//               ),
//
//
//             ]else ...[
//               Column(
//                 children: [
//                   Padding(
//                       padding: const EdgeInsets.only(top: 30, bottom: 30),
//                       child: Container(
//                           decoration: BoxDecoration(border: Border.all(color: Color(0x34ffffff),width: 1),borderRadius: BorderRadius.circular(20)),
//                           child:
//
//                           Padding(
//                               padding: const EdgeInsets.all(20),
//                               child: Column(
//                                   children: [
//                                     Container(height: 200,
//                                         width: 200,
//                                         child: Container(
//
//                                             child: PieChart(
//                                                 PieChartData(
//                                                     sections: [
//                                                       PieChartSectionData(
//                                                         gradient: LinearGradient(colors: [Color(0xffFFC700),Color(0xff997700)]),
//                                                         value: 75,
//                                                         title: '',
//
//                                                         radius: 20,
//                                                         titleStyle: TextStyle(
//                                                           fontSize: 16,
//                                                           fontWeight: FontWeight.bold,
//                                                           color: Theme.of(context).colorScheme.onPrimary,
//                                                         ),
//                                                       ),
//                                                       PieChartSectionData(
//                                                         gradient:
//                                                         LinearGradient(
//                                                             begin: Alignment.centerLeft,
//                                                             end: Alignment.centerRight,
//
//                                                             colors: [Color(0xFFDD6762),Color(0xFFDD695E).withOpacity(0.8)]),
//                                                         value: 25,
//                                                         title: '',
//
//                                                         radius: 20,
//                                                         titleStyle: TextStyle(
//                                                           fontSize: 16,
//                                                           fontWeight: FontWeight.bold,
//                                                           color: Theme.of(context).colorScheme.onPrimary,
//                                                         ),
//                                                       ),]
//                                                 )
//                                             )
//                                         )
//                                     ),
//                                     Padding(
//                                       padding: const EdgeInsets.only(top: 20.0,bottom: 20.0),
//                                       child: Row(
//                                         mainAxisAlignment: MainAxisAlignment.center,
//                                         children: [
//                                           Container(
//                                               height: 30,
//                                               decoration:BoxDecoration(gradient:LinearGradient(colors: [Color(0xffFFC700),Color(0xff997700)]),borderRadius: BorderRadius.circular(4)),
//                                               child: Padding(
//                                                 padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
//                                                 child: Text("Spent"),
//                                               )),
//                                           SizedBox(width: 10),
//
//                                           Container(
//                                             height: 30,
//                                             decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xFFDD6762),Color(0xFFDD695E).withOpacity(0.8)]),borderRadius: BorderRadius.circular(4)),
//                                             child:
//                                             Padding(
//                                                 padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
//                                                 child: Text("Borrow")),
//                                           )
//                                         ],
//                                       ),
//                                     )
//                                   ]
//                               )
//                           )
//                       )
//                   ),
//
//
//                   Container(
//                     width: 380,
//                     decoration: BoxDecoration(
//                         border: Border.all(color: Color(0x32ffffff)),
//                         gradient: LinearGradient(colors: [Color(0x5b5b5b),Color(0xff5B5B5B),]),borderRadius: BorderRadius.circular(10)),
//
//                     child: Row(
//                       children: [
//                         Padding(
//                           padding: const EdgeInsets.all(10.0),
//                           child: Text("Your Balance:",style: TextStyle(color: Colors.white,fontSize: 16,fontWeight: FontWeight.w500),),
//                         ),
//                         SizedBox(width: 5),
//                         Padding(
//                           padding: const EdgeInsets.only(top: 10,bottom:10 ),
//                           child: Text("₹ 1000",style: TextStyle(color: Theme.of(context).colorScheme.primary,fontSize: 16),),
//                         ),Spacer(),
//                         Padding(
//                           padding: const EdgeInsets.only(right: 10),
//                           child: Text("Yet to pay",style: TextStyle(color: Color(
//                               0x80ffffff)),),
//                         )
//                       ],
//                     ),
//                   ),
//
//                   Padding(
//                     padding: const EdgeInsets.only(top: 15,bottom: 30),
//                     child: ElevatedButton(onPressed: (){
//
//                     }, child:Padding(
//                       padding: const EdgeInsets.only(bottom: 30),
//                       child: Container(decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xff5b5b5b),Color(
//                           0xff333131)]),borderRadius: BorderRadius.circular(40)),
//
//                         child: ElevatedButton(onPressed: (){
//
//                           _modalBottomSheetMenu();
//
//
//                         }, child: Text("View Summary",style: TextStyle(color: Colors.white),)
//                           ,style: ElevatedButton.styleFrom(
//                             backgroundColor: Colors.transparent,
//                             minimumSize: Size(MediaQuery.of(context).size.width, 50),
//                             shape: RoundedRectangleBorder(
//                               borderRadius: BorderRadius.circular(40),
//                             ),
//                           ),),
//                       ),
//                     ),),
//                   ),
//                   Padding(
//                     padding: const EdgeInsets.only(bottom: 30),
//                     child: Row(
//                       children: [
//                         Text(
//                           "Your Expenses",
//                           style: TextStyle(fontSize: 24, fontWeight: FontWeight.w400),
//                         ),
//                         Spacer(),
//                         Icon(Icons.sort),
//                       ],
//                     ),
//                   ),
//
//                   Container(
//                     height: 300,
//                     child: ListView.builder(itemCount: yourExpenseList.length,itemBuilder: (context,index){
//                       return Padding(
//                         padding: const EdgeInsets.only(top: 10,bottom: 10),
//                         child: Container(
//                           width: 380,
//                           decoration: BoxDecoration(color: Color(0x1affffff),borderRadius: BorderRadius.circular(10)),
//                           child: ListTile(
//                             title: Row(
//                               children: [
//                                 Expanded(child: Text("${yourExpenseList[index]}",style: TextStyle(color: Colors.white, fontWeight: FontWeight.w400,fontSize: 24))),
//                                 Text("₹${expense[index]}",style: TextStyle(color: Theme.of(context).colorScheme.primary,fontSize: 20, fontWeight: FontWeight.w400))
//                               ],
//
//                             ),subtitle: Row(
//                               children: [Expanded(child: Text("${categoryList[index]}",style: TextStyle(color: Color(0x80ffffff), fontWeight: FontWeight.w400,fontSize: 18))),
//                                 Text("₹${expense[index]}",style: TextStyle(color: Color(0x80ffffff), fontWeight: FontWeight.w400,fontSize: 18))]
//
//                           ),
//                           ),
//                         ),
//                       );
//
//
//                     }
//
//
//
//
//                     ),
//                   )
//                 ],
//               )
//             ]
//           ],
//         ),
//       ),
//     );
//   }
//   void _modalBottomSheetMenu(){
//     String text = "Summary";
//     showModalBottomSheet(
//         context: context,
//         builder: (builder){
//           return  Container(
//               child: Column(
//
//                   children:[
//                     Padding(
//                       padding: const EdgeInsets.only(top: 30, bottom: 30,left: 10,right: 10),
//                       child: Row(
//                         children: [
//                           Text(
//                             "${text}",
//                             style: TextStyle(fontSize: 24, fontWeight: FontWeight.w400),
//                           ),
//                           Spacer(),
//                           IconButton(onPressed: (){
//                             Navigator.pop(context);
//                           }, icon: Icon(Icons.close),)
//                         ],
//                       ),
//                     ),
//                     Expanded(
//                       child: ListView.builder(itemCount: obj!.maindata!.length,itemBuilder: (context,index){
//                         return Padding(
//                           padding: const EdgeInsets.only(left: 16.0,right: 16.0,bottom: 5),
//                           child: Container(
//                             color: Color(0x1affffff),
//                             child: Theme(
//                                 data: Theme.of(context).copyWith(dividerColor: Colors.transparent),
//                                 child: ExpansionTile(
//
//
//                                     title: Row(
//                                       children: [
//
//                                         Expanded(child: Text(obj!.maindata![index].name!,style: TextStyle(color: Theme.of(context).colorScheme.onPrimary,fontWeight: FontWeight.w500),)),
//                                         Text("₹ ${obj!.maindata![index].amount!}", style: TextStyle(color: Colors.green,fontWeight: FontWeight.w500)),
//                                       ],
//                                     ), children: [
//                                   for(var subIndex = 0; subIndex <obj!.maindata![index].subdata!.length; subIndex++)
//                                     ListTile(
//                                       title: Row(
//                                         children: [
//                                           Icon(Icons.local_gas_station_outlined), SizedBox(width: 7),
//                                           Expanded(child: Text(
//                                               "${obj!.maindata![index].subdata![subIndex].heading!}",
//                                               style: TextStyle(
//                                                   color: Colors.white, fontWeight: FontWeight.w400))),
//                                           Text("${obj!.maindata![index].subdata![subIndex].subamount!}",
//                                               style: TextStyle(
//                                                   color: Colors.white, fontWeight: FontWeight.w400))
//                                         ],
//                                       ),
//                                     ),
//                                 ]
//                                 )),
//                           ),
//                         );
//                       }),
//                     ),
//                   ]));}
//
//     );}
//
//  Widget peopleCata (String assetpath, String peopleCataText, ){
//     return Padding(
//       padding: const EdgeInsets.only(right: 10),
//       child: Container(
//         decoration: BoxDecoration(
//           borderRadius: BorderRadius.circular(10),
//           border: Border.all(width: 1,color: Color(0xFFEB1D23)),
//         ),
//         child: Column(crossAxisAlignment: CrossAxisAlignment.center,
//           children: [
//           SizedBox(height: 10,),
//           ClipOval(
//             child: Container(
//               height: 42,
//               width: 42,
//               decoration: BoxDecoration(
//                 //rec
//                 //shape: BoxShape.circle,
//                 gradient: LinearGradient(colors: [Color(0xFFEB1D23),Color(0xFFEB1D23).withOpacity(0.0)],
//                 begin: Alignment.centerLeft,
//                   end: Alignment.centerRight
//                 ),
//               ),
//               child: Padding(
//                 padding: const EdgeInsets.all(1.0),
//                 child: Container(
//                   // height: 38,
//                   // width: 38,
//                   decoration: BoxDecoration(
//                     shape: BoxShape.circle,
//                     image: DecorationImage(image: AssetImage(assetpath),
//                         fit: BoxFit.cover
//                     ),
//                   ),
//                 ),
//               ),
//
//             ),
//           ),
//             SizedBox(height: 10,),
//             SizedBox(width: 60,
//               child: Padding(
//                 padding: const EdgeInsets.only(left: 3,right: 3),
//                 child: Text(peopleCataText,style: TextStyle(
//                     fontSize: 12,
//                     fontWeight: FontWeight.w400,
//                     color: Colors.white,
//                     fontFamily: "FontPoppins"),textAlign: TextAlign.center,overflow: TextOverflow.ellipsis,),
//               ),
//             ),
//           ],
//         )
//       ),
//     );
//  }
//
//   Widget cata(String cateCataIcons, String cateCatatext,){
//
//     return Padding(
//       padding: const EdgeInsets.only(right: 10),
//       child: Container(
//         decoration: BoxDecoration(
//           border: Border.all(width: 1,color: Colors.white10),
//             borderRadius: BorderRadius.circular(10),
//         ),
//         child: Padding(
//           padding: const EdgeInsets.only(right: 10),
//           child: Column(crossAxisAlignment: CrossAxisAlignment.center,
//             children: [
//               Container(
//                 decoration: BoxDecoration(
//                   borderRadius: BorderRadius.circular(10),
//                 ),
//                 child: Padding(
//                   padding: const EdgeInsets.all(20),
//                   child: SvgPicture.asset(cateCataIcons),
//                 ),
//               ),
//               SizedBox(height: 5,),
//               Text(cateCatatext,style: TextStyle(color: Colors.white,
//                   fontSize: 15,
//                   fontWeight: FontWeight.w400,
//                   fontFamily: "FontPoppins"))
//             ],
//           ),
//         ) ,
//
//       ),
//     );
//
//   }
//
//
// }
//
