import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:rydyt_expense_v_one/test_response.dart';
import 'package:percent_indicator/percent_indicator.dart';
import 'package:toggle_switch/toggle_switch.dart';

class Progressbar extends StatefulWidget {
  const Progressbar({super.key});

  @override
  State<Progressbar> createState() => _ProgressbarState();
}

class _ProgressbarState extends State<Progressbar> {
  Autogenerated? obj;
  double total = 0;
  Color getColorForName(String name) {
    switch (name) {
      case 'Kushang':
        return Colors.red;
      case 'Deepthi':
        return Colors.orange;
      case 'Ram':
        return Colors.green;
      case 'khalil':
        return Colors.blue;
      case 'mahesh':
        return Colors.purple;
      default:
        return Colors.grey;
    }
  }

  void initState() {
    readjson();
    super.initState();

  }

  Future<void> readjson() async {
    final String response = await rootBundle.loadString('assets/test.json');
    final data = await json.decode(response);
    obj = Autogenerated.fromJson(data);

    print("obj -- ${obj}");
    if (obj?.maindata != null) {
      double subtotal = 0;
      for (var entry in obj!.maindata!) {
        print("amount -- ${entry.amount}");
        subtotal += entry.amount as double;
      }
      setState(() {
        total = subtotal;
      });
    } else {
      print('maindata is null');
    }
  }

  List colorSingleScroll = [Color(0xFF105CF8),Color(0xFFFEBC008),Color(0xFF15C872),Color(0xFFE02020),Colors.purple,];



  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body: Padding(
        padding: const EdgeInsets.only(top:16, left: 16, right: 16),
        child: ListView(
            children: [
              Padding(
                padding: const EdgeInsets.only(top: 30, bottom: 30),
                child: Row(
                  children: [
                    Text(
                      "Ride Expenses",
                      style: TextStyle(
                          color: Colors.white,
                          fontSize: 24, fontWeight: FontWeight.w400),
                    ),
                    Spacer(),
                    InkWell(
                        onTap: (){},
                        child: SvgPicture.asset("assets/icons/cross_icon.svg"))
                  ],
                ),),
              Container(
                  decoration: BoxDecoration(border: Border.all(color: Color(0x34ffffff)),borderRadius: BorderRadius.circular(10),gradient: LinearGradient(
                      begin: Alignment.topCenter,
                      end: Alignment.bottomCenter,
                      colors: [Color(0xff1E1E1E),Color(0xff000000),])),
                  width: double.infinity,
                  child: Padding(
                    padding: const EdgeInsets.all(20.0),
                    child: Column(
                        children: [
                          Center(child: Text("₹ ${total}",style: TextStyle(fontSize: 36,color: Colors.white),)),

                          Text("Total Expenses",style: TextStyle(fontSize: 18,fontWeight: FontWeight.w400,color: Color(0x99ffffff)),),
                          SizedBox(height: 30,),
                          ClipRRect(
                            borderRadius: BorderRadius.circular(10),
                            child: Container(
                              decoration: BoxDecoration(borderRadius: BorderRadius.circular(10)),
                              child: Row(
                                  children:
                                  obj!.maindata!.map((entry){
                                    double percentage = entry.amount!.toDouble();
                                    return Expanded(
                                      flex: (percentage*100).round(),
                                      child: Container(
                                        height: 10,
                                        decoration: BoxDecoration(
                                          color: getColorForName(entry.name!),
                                        ),
                                      ),
                                    );

                                  }).toList()

                              ),
                            ),
                          ),
                          SizedBox(height: 30,),
                          SingleChildScrollView(
                            scrollDirection: Axis.horizontal,
                            child: Row(
                              children: [
                                for (int index = 0; index < obj!.maindata!.length; index++)
                                  Padding(
                                    padding: const EdgeInsets.all(10),
                                    child: Container(
                                      decoration: BoxDecoration(
                                          color: Color(0x1affffff),
                                          border: Border.all(color: colorSingleScroll[index],width: 1),
                                          borderRadius: BorderRadius.circular(10)),
                                      child: Center(
                                        child: Padding(
                                          padding: const EdgeInsets.only(left: 15,right: 15,top: 10,bottom: 10),
                                          child: Column(
                                            children: [
                                              Text("${obj!.maindata![index].name}", style: TextStyle(fontSize: 12, fontWeight: FontWeight.w400,color: Colors.white.withOpacity(0.9)),),
                                              Text("₹${obj!.maindata![index].amount}", style: TextStyle(fontSize: 17, fontWeight: FontWeight.w400,color: Colors.white.withOpacity(0.9)),),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ),
                                  )

                              ],
                            ),
                          ),]
                    ),
                  )
              ),
              Padding(
                padding: const EdgeInsets.only(top: 30.0),
                child: Container(
                  width: double.infinity,
                  decoration: BoxDecoration(
                      gradient: LinearGradient(
                          colors: [Color(0xFF535353).withOpacity(0.0),Color(0xFF5B5B5B).withOpacity(0.5)],
                      ),
                      borderRadius: BorderRadius.circular(10),
                      border: Border.all(color: Colors.white12,width: 1),
                  ),
                  child: Row(
                    children: [
                      Padding(
                        padding: const EdgeInsets.all(10.0),
                        child: Text("Your Balance:",style: TextStyle(color: Colors.white,fontSize: 16,fontWeight: FontWeight.w500),),
                      ),
                      SizedBox(width: 5),
                      Padding(
                        padding: const EdgeInsets.only(top: 10,bottom:10 ),
                        child: Text("₹ 1000",style: TextStyle(color: Colors.green,fontSize: 16,fontWeight: FontWeight.w500),),
                      ),Spacer(),
                      Padding(
                        padding: const EdgeInsets.only(right: 10),
                        child: Text("Yet to pay",style: TextStyle(color: Colors.white.withOpacity(0.5)),),
                      )
                    ],
                  ),
                ),
              ),
              Padding(
                padding: const EdgeInsets.only(top: 15.0,bottom: 30),
                child: InkWell(
                  onTap: (){

                  },
                  child: Container(
                      width: double.infinity,
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                            colors: [Color(0xFFD9D9D9).withOpacity(0.2),Color(0xFF5B5B5B).withOpacity(0.4),]),
                        borderRadius: BorderRadius.circular(40),
                        border: Border.all(color: Colors.white12,width: 1),
                      ),
                    child: Center(
                      child: Padding(
                        padding: const EdgeInsets.only(top: 11,bottom: 11),
                        child: Text("View Summary",
                            style: TextStyle(
                                fontSize: 12,
                                fontWeight: FontWeight.w400,
                                color: Colors.white.withOpacity(0.7)
                            )),
                      ),
                    ),
                  ),
                ),
              ),
              Text("Expenses for this ride",style: TextStyle(fontSize: 24,fontWeight: FontWeight.w400,color: Colors.white,fontFamily: "FontPoppins"),),
              Padding(
                padding: const EdgeInsets.only(top: 30,bottom: 30),
                child: Row(
                    children: [
                      InkWell(
                        onTap: (){},
                        child: Container(
                            decoration:BoxDecoration(
                                gradient: LinearGradient(
                                    begin: Alignment.centerLeft,
                                    end: Alignment.centerRight,
                                    colors: [Color(0xffEB1D23),Color(0xff840004),]),borderRadius: BorderRadius.circular(40)),
                            child: Padding(
                              padding: const EdgeInsets.only(left: 15,right: 15,top: 5,bottom: 5),
                              child: Text("All",style: TextStyle(color: Colors.white),),
                            )),
                      ),
                      SizedBox(width: 10,),
                      InkWell(
                        onTap: (){

                        },
                        child: Container(
                            decoration: BoxDecoration(
                                gradient: LinearGradient(
                                    colors:[Color(0xFFD9D9D9).withOpacity(0.3),Color(0xFF5B5B5B).withOpacity(0.5),]
                                        ,begin: Alignment.centerLeft,
                                  end: Alignment.centerRight,
                                ),
                                borderRadius: BorderRadius.circular(40)),
                            child: Padding(
                              padding: const EdgeInsets.only(left: 15,right: 15,top: 5,bottom: 5),
                              child: Text("Only me",style: TextStyle(color: Colors.white),),
                            )),
                      ),
                    ],
                    //
                  ),
              ),
              Row(
                children: [
                  Expanded(child: Text("23 Apr 2024",style: TextStyle(fontSize: 12,fontWeight: FontWeight.w400,color: Colors.white.withOpacity(0.9)),)),
                  Text("₹ ${total}",style: TextStyle(fontSize: 12,fontWeight: FontWeight.w400,color: Colors.white.withOpacity(0.9)))
                ],
              ),
              Container(
                  width: double.infinity,
                  child: ListView.builder(
                      itemCount: obj?.maindata?.length,
                      shrinkWrap: true,
                      itemBuilder: (context, index) {
                        return Padding(
                          padding: const EdgeInsets.only(top: 10.0,bottom: 10.0),
                          child: Container(
                            decoration: BoxDecoration(
                                color: Color(0x1affffff),
                                borderRadius: BorderRadius.circular(10)),
                            child: ListTile(
                                title: Row(
                                  children: [
                                    Expanded(child: Text("${obj!.maindata![index].name}",style: TextStyle(fontSize: 16,fontWeight: FontWeight.w400,color: Colors.white.withOpacity(0.9)))),
                                    Text("₹ ${obj!.maindata![index].amount}",style: TextStyle(fontSize: 16,fontWeight: FontWeight.w400,color: Colors.white.withOpacity(0.9))),
                                  ],
                                ),
                                subtitle: Column(
                                    children: [
                                      Row(
                                        children: [
                                          Expanded(child: Text("${obj!.maindata![index].subdata![0].heading}",style: TextStyle(fontSize: 12,fontWeight: FontWeight.w400,color: Colors.white.withOpacity(0.5)))),
                                          Text("${obj!.maindata![index].subdata![0].time}",style: TextStyle(fontSize: 12,fontWeight: FontWeight.w400,color: Colors.white.withOpacity(0.5))),
                                        ],
                                      )])),
                          ),
                        );
                      }))]
        ),
      ),
    );
  }





}
